# 学习张量（Tensor）是什么，与 NumPy 数组的区别
## 掌握：
    torch.tensor(), torch.zeros(), torch.ones(), torch.randn()
    .dtype, .device, .shape
    张量在 CPU/GPU 上的移动（.to(device)）
    创建不同类型的张量并转换设备（如有 GPU）
    用 PyTorch 创建一个 3×3 的随机张量，并将其移到 GPU（如果可用）



In [17]:
import numpy as np
import torch

# 正确的设备选择
device = (
    "cuda" if torch.cuda.is_available()
    else "mps" if hasattr(torch.backends, 'mps') and torch.backends.mps.is_available()
    else "cpu"
)


test1_np = np.random.randn(100) * 10
test1_np = test1_np.reshape((10,10))
# np转tensor
test1_tensor = torch.tensor(test1_np)
# 生成大小为5 * 5 的tensor全0矩阵
test2_tensor = torch.zeros((5,5))
# 生成大小为3 * 3 的tensor全1矩阵
test3_tensor = torch.ones((3,3))
# 生成长度为25的向量
test4_tensor = torch.randn((5 * 5))
# 转成为5 * 5 的矩阵
test5_tensor = test4_tensor.reshape((5,5))
# 转到gpu再转回cpu
test5_tensor.to(device).cpu()

tensor([[-0.3920,  1.3220,  0.6911,  0.8139, -1.0302],
        [ 0.1355, -1.3730, -1.0736, -0.5991, -0.5805],
        [-1.2461, -0.1652,  0.6331,  0.6351, -0.7224],
        [ 0.5479,  0.7772, -1.8687,  0.2712, -1.4497],
        [-0.4130, -0.0933,  1.4278,  0.7758,  1.7876]])

# 基本运算：加减乘除、点积（torch.mm, @）、转置（.T）
## 索引与切片（类似 NumPy）
    形状变换：view(), reshape(), unsqueeze(), squeeze()
    广播机制（Broadcasting）
    与 NumPy 互转：.numpy(), torch.from_numpy(),使用torch.from_numpy更加安全，使用tensor.Tensor在非float类型下会与预期不符。
    实现两个矩阵相乘，并 reshape 成 (9,) 向量
    torch.tensor 适用于从任何类型的数据创建独立的张量，并不与原始数据共享内存，适合需要深拷贝和数据隔离的场景。
    torch.from_numpy 适合从 NumPy 数组快速创建张量，且共享内存，适合在需要高效数据传递和共享内存的场景下使用。

In [100]:
import torch

# 生成长度为25的向量
test5_tensor = torch.randn((5 * 5))

test5_tensor = test5_tensor.view((5,5))

tes6_tensor = test5_tensor.reshape((5*5))


# 生成一个0-10的tensor
test7_tensor = torch.arange(0,9)

test8_tensor = test7_tensor.view((3,3))
# 扩展维度
test9_tensor = test8_tensor.unsqueeze(2)
# 降维,把维度为1的降下来
test10_tensor = test9_tensor.squeeze(2)

# 可广播，会像高维补齐
c = torch.empty(5, 1, 4, 1)
d = torch.empty(   3, 1, 1)
(c + d).size()

(c * d).reshape(-1)

test2_np = (np.random.randn(4) * 10).reshape((2,2))
test12_tensor = torch.from_numpy(test2_np)
test13_tensor = torch.tensor(test2_np)
test2_np,test12_tensor,test13_tensor

(array([[-13.50983527, -10.19783871],
        [ -1.04400407,  15.86396078]]),
 tensor([[-13.5098, -10.1978],
         [ -1.0440,  15.8640]], dtype=torch.float64),
 tensor([[-13.5098, -10.1978],
         [ -1.0440,  15.8640]], dtype=torch.float64))

## 自动求导（Autograd）原理与实践
## 理解计算图（Computation Graph）
    requires_grad=True
    .backward() 和 .grad
    阻断梯度：.detach(), with torch.no_grad():
    梯度清零：.zero_grad()
    定义 y = x² + 2x + 1，手动计算 dy/dx 在 x=3 处的值，并用 Autograd 验证

In [110]:
import torch

def f(x):
    return x ** 2 + 2 * x +1

def f_grad(x):
    return 2 * x +2


test_x = torch.tensor(1.0,requires_grad=True)
y = f(test_x)
y.backward()

print(f'手动计算梯度：{f_grad(test_x.item())},自动计算梯度：{test_x.grad}')

手动计算梯度：4.0,自动计算梯度：4.0
